### ISSUE TITLE
Quick swipe right on slider closes the drawer on mobile

### ISSUE THREAD

**Issue by ojafero** [Greenstand/treetracker-web-map-client#1149] opened 2022-10-26 23:04 UTC
https://user-images.githubusercontent.com/53157755/198154858-ccee1463-7277-46b4-91db-eb8086b1e464.mp4

**Comment by ojafero** [comment] 2022-10-26 23:05
I'm working on it.

**Comment by dadiorchen** [comment] 2023-03-18 09:44
This is not a bug, this is intentional design for the UX, quick swipe to collapse the draw

**Comment by dadiorchen** [comment] 2023-06-30 03:21
Let's achieve the code there and wait for the feedback from end user, if this become critical, we will back to here and merge the code, but for now, to keep the drawer simple, I will close this PR and keep monitoring this bug.

**Closed by dadiorchen** 2023-06-30 03:21 UTC
Labels: bug
